
[workspace]
members = [
    "base_roulante",
    "herkulex",
    "can_bus"
]


[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations

